### PR TITLE
Image upload fixed for 10MB max size

### PR DESCRIPTION
**Pull request by ultra-pool**
Change from 2MB
const sizeLimit = sizeLimitInMB * 1024 * 1024;

To 10MB image upload
const sizeLimit = sizeLimitInMB * 1024 * 1024 * 10;

^^Per abeikverdi Hollaex dev.
Thank you for the help.

### CODE REVIEW

**Comment by ultra-pool** [comment]
@abeikverdi please review and push to main so we can update our pro cloud and make our community happy again. Thank you for the help.

**Comment by abeikverdi** [comment]
This is already fixed in develop branch.

**Comment by ultra-pool** [comment]
@abeikverdi When will it pushed to master? I was told it was going to be in the next patch but it's not in the new patch today.

**Comment by abeikverdi** [comment]
There hasnt been any release today.

**Comment by ultra-pool** [comment]
Oh discord release channel said 2.2.3 was released today.

**Pull request closed without merging**
